### ISSUE TITLE
Optionally hide bloated elements

### ISSUE THREAD

**Issue by mitchazj** [klaussinani/ao#103]
**Is your feature request related to a problem? Please describe.**
I find the extra visuals added by Microsoft to the top of the window to be quite distracting.

**Describe the solution you'd like**
A menu checkbox called "Hide Office365 Menu" that hotswaps something along the lines of the following CSS:
```CSS
.o365header {
    display: none;
}
#notifications {
    display: none;
}
.tasksToolbar.with-subline {
    padding-top: 4px;
}
```

**Additional context**
Without the above CSS:
[Screenshot](https://imgur.com/nDVycWq) (Ewww)

With the above CSS injected:
[Screenshot](https://imgur.com/bGgZbx1)
